export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const SAVE_BOOK_SUCCESS = "SAVE_BOOK_SUCCESS";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
